### ISSUE TITLE
password gets logged

### ISSUE THREAD

**Issue by overheadhunter** [markeytos/code-sign-action#2]
If I'm not mistaken, this action prints the password to debug log. Only GitHub Actions' password redaction keeps it from leaking. This isn't something one wants to rely on:

https://github.com/markeytos/code-sign-action/blob/8603a72958d4892cfda24a9ebc1dc5b9c42058a4/index.ts#L45-L46

See example https://github.com/coding-flamingo/CodeSignConsoleApp/runs/2631128254?check_suite_focus=true#step:4:10

**Comment by igalfsg** [comment]
Thanks for the catch! just removed it from the logs!
